default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost

development:
  <<: *default
  database: todo_dev

test: &test
  <<: *default
  database: todo_test

cucumber:
  <<: *test
